version: "3.3"

services:
  app:
    build: .
    restart: always
    networks:
      - traefik
      - internal
    depends_on:
      - postgres_primary
    secrets:
      - nutritionix-api.id
      - nutritionix-api.key
      - postgres.password
      - tesco-api.key
    environment:
      - POSTGRES_HOST=postgres_primary
      - POSTGRES_DATABASE=macro_tracker
      - POSTGRES_USER=macro_tracker
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres.password
      - TESCO_API_SECRET_FILE=/run/secrets/tesco-api.key
      - NUTRITIONIX_API_ID_FILE=/run/secrets/nutritionix-api.id
      - NUTRITIONIX_API_KEY_FILE=/run/secrets/nutritionix-api.key
    volumes:
      - ./logs:/logs
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik_default
      - traefik.http.routers.macros-api.rule=Host(`macros.tatsu.casa`, `www.macros.tatsu.casa`)
      - traefik.http.routers.macros-api.tls.certresolver=letsencrypt
      - traefik.http.routers.macros-api.middlewares=strip-www@file,authelia@file

  postgres_primary:
    image: postgres:10.1-alpine
    restart: always
    networks:
      - internal
    secrets:
      - postgres.password
    environment:
      - POSTGRES_DATABASE=macro_tracker
      - POSTGRES_USER=macro_tracker
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres.password
    volumes:
      - postgres-primary-data:/var/lib/postgresql/data

volumes:
  postgres-primary-data:

secrets:
  nutritionix-api.id:
    file: ./src/config/secrets/nutritionix-api.id
  nutritionix-api.key:
    file: ./src/config/secrets/nutritionix-api.key
  postgres.password:
    file: ./src/config/secrets/postgres.password
  tesco-api.key:
    file: ./src/config/secrets/tesco-api.key

networks:
  internal:
    external: false
  traefik:
    external:
      name: traefik_default
