version: "3.3"

services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    restart: always
    networks:
      - traefik
      - internal
    depends_on:
      - redis
      - postgres_primary
    secrets:
      - nutritionix-api.id
      - nutritionix-api.key
      - postgres.password
      - session.secret
      - tesco-api.key
    environment:
      - NPM_EXECPATH=yarn
      - npm_execpath=yarn
      - RUNNING_IN=docker
    volumes:
      - ./logs:/logs
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik_default
      - traefik.http.routers.macros-api.rule=Host(`macros.tatsu.casa`, `www.macros.tatsu.casa`)
      - traefik.http.routers.macros-api.tls.certresolver=letsencrypt
      - traefik.http.routers.macros-api.middlewares=strip-www@file,authelia@file

  postgres_primary:
    image: postgres:10.1-alpine
    restart: always
    networks:
      - internal
    secrets:
      - postgres.password
    environment:
      - POSTGRES_DATABASE=macro_tracker
      - POSTGRES_USER=macro_tracker
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres.password
    volumes:
      - postgres-primary-data:/var/lib/postgresql/data

  redis:
    image: redis:3.2-alpine
    restart: always
    networks:
      - internal
    command: redis-server --appendonly yes
    volumes:
      - redis-data:/data

volumes:
  postgres-primary-data:
  redis-data:

secrets:
  nutritionix-api.id:
    file: ./src/config/secrets/nutritionix-api.id
  nutritionix-api.key:
    file: ./src/config/secrets/nutritionix-api.key
  postgres.password:
    file: ./src/config/secrets/postgres.password
  session.secret:
    file: ./src/config/secrets/session.secret
  tesco-api.key:
    file: ./src/config/secrets/tesco-api.key

networks:
  internal:
    external: false
  traefik:
    external:
      name: traefik_default
