version: "3.3"

services:
  app:
    build: .
    depends_on:
      - postgres
    secrets:
      - postgres-password
      - tesco-api-key
      - nutritionix-api-id
      - nutritionix-api-key
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_DATABASE=macro_tracker
      - POSTGRES_USER=macro_tracker
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres-password
      - TESCO_API_SECRET_FILE=/run/secrets/tesco-api-key
      - NUTRITIONIX_API_ID_FILE=/run/secrets/nutritionix-api-id
      - NUTRITIONIX_API_KEY_FILE=/run/secrets/nutritionix-api-key
    volumes:
      - ./logs:/logs

  postgres:
    image: postgres:10.1-alpine
    secrets:
      - postgres-password
    environment:
      - POSTGRES_DATABASE=macro_tracker
      - POSTGRES_USER=macro_tracker
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres-password
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:

secrets:
  postgres-password:
    file: ./secrets/postgres-password
  tesco-api-key:
    file: ./secrets/tesco-api-key
  nutritionix-api-id:
    file: ./secrets/nutritionix-api-id
  nutritionix-api-key:
    file: ./secrets/nutritionix-api-key
