export const tableWrapper: string;
export const loading: string;
export const tableHeader: string;
export const tableFooter: string;
export const table: string;
export const tableBodyWrapper: string;
export const loadingIconWrapper: string;
export const sortInactive: string;
export const sortable: string;
